version: "3.8"
services:
  flog:
    image: mingrammer/flog:0.4.3
    command: ["flog", "--loop", "--delay", "1s"]
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock
  vector:
    image: timberio/vector:nightly-alpine
    volumes:
    - ./vector:/etc/vector:ro
    - /var/run/docker.sock:/var/run/docker.sock
    command:
    - --config
    - /etc/vector/vector.toml
    depends_on:
    - flog
  prometheus:
    image: prom/prometheus:v2.22.0
    ports:
    - 9090:9090
    volumes:
    - ./prometheus:/etc/prometheus:ro
    command:
    - --config.file=/etc/prometheus/prometheus.yml
    depends_on:
    - vector