[sources.generator]
type = "generator"
lines = ["apple", "orange", "banana"]

[sources.internal_metrics]
type = "internal_metrics"

[sources.host_metrics]
type = "host_metrics"

[sinks.console]
type = "console"
inputs = ["generator"]
target = "stdout"
encoding.codec = "text"

[sinks.prometheus]
type = "prometheus"
inputs = ["internal_metrics", "host_metrics"]
address = "0.0.0.0:1111"
