# GraphQL Playground
[api]
enabled = true
address = "0.0.0.0:8686"

# Underlying host metrics
[sources.host_metrics]
type = "host_metrics"

# Vector internal metrics
[sources.internal_metrics]
type = "internal_metrics"

# Expose Vector and host metrics to Prometheus
[sinks.prometheus]
type = "prometheus"
inputs = ["host_metrics", "internal_metrics"]
address = "0.0.0.0:9090"

#
# Log pipeline
#

# Ingest randomly generated logs
[sources.logs]
type = "docker"
include_containers = ["flog"]

[transforms.json]
type = "json_parser"
inputs = ["logs"]

[transforms.remove_container_metadata]
type = "remove_fields"
inputs = ["json"]
fields = ["container_created_at", "container_id", "container_name"]

[transforms.trim]
type = "remove_fields"
inputs = ["remove_container_metadata"]
fields = ["image", "label", "stream", "timestamp"]
drop_empty = true

[transforms.strip]
type = "remove_fields"
inputs = ["trim"]
fields = ["method", "protocol", "request"]
drop_empty = true

[transforms.sample]
type = "sampler"
inputs = ["trim"]
key_field = "user-identifier"
rate = 5

[sinks.splunk]
type = "splunk_hec"
inputs = ["trim", "strip", "sample"]
host = "http://splunk:8088"
healthcheck = true
token = "${SPLUNK_HEC_TOKEN}"
encoding.codec = "json"

[sinks.raw]
type = "blackhole"
inputs = ["trim"]
print_amount = 10000

[sinks.trimmed]
type = "blackhole"
inputs = ["strip"]
print_amount = 10000

[sinks.sampled]
type = "blackhole"
inputs = ["sample"]
print_amount = 10000
