# GraphQL Playground
[api]
enabled = true
bind = "0.0.0.0:8686"

# Prometheus metrics
[sources.internal_metrics]
type = "internal_metrics"

[sources.host_metrics]
type = "host_metrics"

[sinks.prometheus]
type = "prometheus"
inputs = ["internal_metrics", "host_metrics"]
address = "0.0.0.0:9598"

# Log pipeline
[sources.logs]
type = "docker"
include_containers = ["flog"]

[transforms.json]
type = "json_parser"
inputs = ["logs"]

[transforms.trim]
type = "remove_fields"
inputs = ["json"]
fields = ["container_created_at", "container_id", "container_name", "image", "label", "stream", "timestamp"]
drop_empty = true

[transforms.strip]
type = "remove_fields"
inputs = ["trim"]
fields = ["method", "protocol", "request"]
drop_empty = true

[sinks.raw]
type = "blackhole"
inputs = ["trim"]
print_amount = 10000

[sinks.trimmed]
type = "blackhole"
inputs = ["strip"]
print_amount = 10000
