# GraphQL Playground
[api]
enabled = true
address = "0.0.0.0:8686"

# Underlying host metrics
[sources.host_metrics]
type = "host_metrics"

# Vector internal metrics
[sources.internal_metrics]
type = "internal_metrics"

# Expose Vector and host metrics to Prometheus
[sinks.prometheus]
type = "prometheus"
inputs = ["host_metrics", "internal_metrics"]
address = "0.0.0.0:9090"

#
# Log pipeline
#

# Ingest randomly generated logs
[sources.logs]
type = "generator"
format = "syslog"

[transforms.parse]
type = "remap"
inputs = ["logs"]
source = '''
. = parse_syslog!(.message)
. = encode_json(.)
'''

[transforms.remove_container_metadata]
type = "remap"
inputs = ["parse"]
source = '''
del(.container_created_at)
del(.container_id)
del(.container_name)
'''

[transforms.trim]
type = "remap"
inputs = ["remove_container_metadata"]
source = '''
del(.image)
del(.label)
del(.stream)
del(.timestamp)
'''

[transforms.strip]
type = "remap"
inputs = ["trim"]
source = '''
del(.method)
del(.protocol)
del(.request)
'''

[transforms.sample]
type = "sampler"
inputs = ["trim"]
key_field = "user-identifier"
rate = 5

[sinks.raw]
type = "blackhole"
inputs = ["trim"]
print_amount = 10000

[sinks.trimmed]
type = "blackhole"
inputs = ["strip"]
print_amount = 10000

[sinks.sampled]
type = "blackhole"
inputs = ["sample"]
print_amount = 10000
