# GraphQL Playground
#[api]
#enabled = true

# Prometheus metrics
[sources.internal_metrics]
type = "internal_metrics"

[sources.host_metrics]
type = "host_metrics"

[sinks.prometheus]
type = "prometheus"
inputs = ["internal_metrics", "host_metrics"]
address = "0.0.0.0:1111"

# Log pipeline
[sources.logs]
type = "docker"
include_containers = ["flog"]

[sinks.blackhole]
type = "blackhole"
inputs = ["logs"]
print_amount = 10000